### ISSUE TITLE
Update mobile-nav toggle behavior using Alpine.js

### ISSUE THREAD

**Issue by matteioo** [matteioo/fet-webpage-redesign#9]
Update mobile-navbar toggle behavior using Alpine.js instead of vanilla js. 

Don't forget to use the magic helper `$screen('sm')` from the Alpine.js plugin. Already implemented in `[posts.html]`.

**Comment by M00nD3v** [comment]
The following pages are transitioned from VanilaJS to Alpine.js (entries with a '*' additionally have implemented the scale transition):

- [X] `admin.html`
- [X] `blackboard.html`
- [X] `impressum.html`
- [X] `index.html`*
- [X] `login.html`
- [X] `member-details.html`
- [X] `members.html`
- [X] `post.html`
- [X] `posts.html`
- [ ] `fotos.html`
